//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Basic.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace JesseFreeman.BasicInterpreter.AntlrGenerated {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BasicParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public interface IBasicListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] BasicParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] BasicParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] BasicParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] BasicParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.lineWithoutNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineWithoutNumber([NotNull] BasicParser.LineWithoutNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.lineWithoutNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineWithoutNumber([NotNull] BasicParser.LineWithoutNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.amperoper"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmperoper([NotNull] BasicParser.AmperoperContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.amperoper"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmperoper([NotNull] BasicParser.AmperoperContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.linenumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinenumber([NotNull] BasicParser.LinenumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.linenumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinenumber([NotNull] BasicParser.LinenumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.amprstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmprstmt([NotNull] BasicParser.AmprstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.amprstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmprstmt([NotNull] BasicParser.AmprstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] BasicParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] BasicParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.vardecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVardecl([NotNull] BasicParser.VardeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.vardecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVardecl([NotNull] BasicParser.VardeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.printstmt1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintstmt1([NotNull] BasicParser.Printstmt1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.printstmt1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintstmt1([NotNull] BasicParser.Printstmt1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.getstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGetstmt([NotNull] BasicParser.GetstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.getstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGetstmt([NotNull] BasicParser.GetstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.letstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetstmt([NotNull] BasicParser.LetstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.letstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetstmt([NotNull] BasicParser.LetstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.variableassignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableassignment([NotNull] BasicParser.VariableassignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.variableassignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableassignment([NotNull] BasicParser.VariableassignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.stringVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringVarDecl([NotNull] BasicParser.StringVarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.stringVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringVarDecl([NotNull] BasicParser.StringVarDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.relop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelop([NotNull] BasicParser.RelopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.relop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelop([NotNull] BasicParser.RelopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.neq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNeq([NotNull] BasicParser.NeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.neq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNeq([NotNull] BasicParser.NeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.ifstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfstmt([NotNull] BasicParser.IfstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.ifstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfstmt([NotNull] BasicParser.IfstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.forstmt1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForstmt1([NotNull] BasicParser.Forstmt1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.forstmt1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForstmt1([NotNull] BasicParser.Forstmt1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.forstmt2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForstmt2([NotNull] BasicParser.Forstmt2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.forstmt2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForstmt2([NotNull] BasicParser.Forstmt2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.nextstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNextstmt([NotNull] BasicParser.NextstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.nextstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNextstmt([NotNull] BasicParser.NextstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.inputstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInputstmt([NotNull] BasicParser.InputstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.inputstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInputstmt([NotNull] BasicParser.InputstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.readstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadstmt([NotNull] BasicParser.ReadstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.readstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadstmt([NotNull] BasicParser.ReadstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.dimstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDimstmt([NotNull] BasicParser.DimstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.dimstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDimstmt([NotNull] BasicParser.DimstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.gotostmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGotostmt([NotNull] BasicParser.GotostmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.gotostmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGotostmt([NotNull] BasicParser.GotostmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.gosubstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGosubstmt([NotNull] BasicParser.GosubstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.gosubstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGosubstmt([NotNull] BasicParser.GosubstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.pokestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPokestmt([NotNull] BasicParser.PokestmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.pokestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPokestmt([NotNull] BasicParser.PokestmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.callstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallstmt([NotNull] BasicParser.CallstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.callstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallstmt([NotNull] BasicParser.CallstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.hplotstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHplotstmt([NotNull] BasicParser.HplotstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.hplotstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHplotstmt([NotNull] BasicParser.HplotstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.vplotstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVplotstmt([NotNull] BasicParser.VplotstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.vplotstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVplotstmt([NotNull] BasicParser.VplotstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.plotstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlotstmt([NotNull] BasicParser.PlotstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.plotstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlotstmt([NotNull] BasicParser.PlotstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.ongotostmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOngotostmt([NotNull] BasicParser.OngotostmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.ongotostmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOngotostmt([NotNull] BasicParser.OngotostmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.ongosubstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOngosubstmt([NotNull] BasicParser.OngosubstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.ongosubstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOngosubstmt([NotNull] BasicParser.OngosubstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.vtabstmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVtabstmnt([NotNull] BasicParser.VtabstmntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.vtabstmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVtabstmnt([NotNull] BasicParser.VtabstmntContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.htabstmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtabstmnt([NotNull] BasicParser.HtabstmntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.htabstmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtabstmnt([NotNull] BasicParser.HtabstmntContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.himemstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHimemstmt([NotNull] BasicParser.HimemstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.himemstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHimemstmt([NotNull] BasicParser.HimemstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.lomemstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLomemstmt([NotNull] BasicParser.LomemstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.lomemstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLomemstmt([NotNull] BasicParser.LomemstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.datastmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatastmt([NotNull] BasicParser.DatastmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.datastmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatastmt([NotNull] BasicParser.DatastmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.datum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatum([NotNull] BasicParser.DatumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.datum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatum([NotNull] BasicParser.DatumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.waitstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWaitstmt([NotNull] BasicParser.WaitstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.waitstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWaitstmt([NotNull] BasicParser.WaitstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.xdrawstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXdrawstmt([NotNull] BasicParser.XdrawstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.xdrawstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXdrawstmt([NotNull] BasicParser.XdrawstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.drawstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrawstmt([NotNull] BasicParser.DrawstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.drawstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrawstmt([NotNull] BasicParser.DrawstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.defstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefstmt([NotNull] BasicParser.DefstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.defstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefstmt([NotNull] BasicParser.DefstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.tabstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTabstmt([NotNull] BasicParser.TabstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.tabstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTabstmt([NotNull] BasicParser.TabstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.speedstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpeedstmt([NotNull] BasicParser.SpeedstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.speedstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpeedstmt([NotNull] BasicParser.SpeedstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.rotstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRotstmt([NotNull] BasicParser.RotstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.rotstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRotstmt([NotNull] BasicParser.RotstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.scalestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScalestmt([NotNull] BasicParser.ScalestmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.scalestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScalestmt([NotNull] BasicParser.ScalestmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.colorstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColorstmt([NotNull] BasicParser.ColorstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.colorstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColorstmt([NotNull] BasicParser.ColorstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.hcolorstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHcolorstmt([NotNull] BasicParser.HcolorstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.hcolorstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHcolorstmt([NotNull] BasicParser.HcolorstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.hlinstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHlinstmt([NotNull] BasicParser.HlinstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.hlinstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHlinstmt([NotNull] BasicParser.HlinstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.vlinstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVlinstmt([NotNull] BasicParser.VlinstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.vlinstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVlinstmt([NotNull] BasicParser.VlinstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.onerrstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnerrstmt([NotNull] BasicParser.OnerrstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.onerrstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnerrstmt([NotNull] BasicParser.OnerrstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.prstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrstmt([NotNull] BasicParser.PrstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.prstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrstmt([NotNull] BasicParser.PrstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.instmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstmt([NotNull] BasicParser.InstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.instmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstmt([NotNull] BasicParser.InstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.storestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStorestmt([NotNull] BasicParser.StorestmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.storestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStorestmt([NotNull] BasicParser.StorestmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.recallstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecallstmt([NotNull] BasicParser.RecallstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.recallstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecallstmt([NotNull] BasicParser.RecallstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.liststmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListstmt([NotNull] BasicParser.ListstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.liststmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListstmt([NotNull] BasicParser.ListstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.popstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPopstmt([NotNull] BasicParser.PopstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.popstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPopstmt([NotNull] BasicParser.PopstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.amptstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmptstmt([NotNull] BasicParser.AmptstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.amptstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmptstmt([NotNull] BasicParser.AmptstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.includestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncludestmt([NotNull] BasicParser.IncludestmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.includestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncludestmt([NotNull] BasicParser.IncludestmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.endstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndstmt([NotNull] BasicParser.EndstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.endstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndstmt([NotNull] BasicParser.EndstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.returnstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnstmt([NotNull] BasicParser.ReturnstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.returnstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnstmt([NotNull] BasicParser.ReturnstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.restorestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRestorestmt([NotNull] BasicParser.RestorestmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.restorestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRestorestmt([NotNull] BasicParser.RestorestmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] BasicParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] BasicParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.func_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_([NotNull] BasicParser.Func_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.func_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_([NotNull] BasicParser.Func_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.signExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSignExpression([NotNull] BasicParser.SignExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.signExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSignExpression([NotNull] BasicParser.SignExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.exponentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExponentExpression([NotNull] BasicParser.ExponentExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.exponentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExponentExpression([NotNull] BasicParser.ExponentExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.multiplyingExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplyingExpression([NotNull] BasicParser.MultiplyingExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.multiplyingExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplyingExpression([NotNull] BasicParser.MultiplyingExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.addingExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddingExpression([NotNull] BasicParser.AddingExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.addingExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddingExpression([NotNull] BasicParser.AddingExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] BasicParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] BasicParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] BasicParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] BasicParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.var_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_([NotNull] BasicParser.Var_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.var_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_([NotNull] BasicParser.Var_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.varname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarname([NotNull] BasicParser.VarnameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.varname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarname([NotNull] BasicParser.VarnameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.varsuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarsuffix([NotNull] BasicParser.VarsuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.varsuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarsuffix([NotNull] BasicParser.VarsuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarlist([NotNull] BasicParser.VarlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarlist([NotNull] BasicParser.VarlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.exprlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprlist([NotNull] BasicParser.ExprlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.exprlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprlist([NotNull] BasicParser.ExprlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.sqrfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSqrfunc([NotNull] BasicParser.SqrfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.sqrfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSqrfunc([NotNull] BasicParser.SqrfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.chrfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChrfunc([NotNull] BasicParser.ChrfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.chrfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChrfunc([NotNull] BasicParser.ChrfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.lenfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLenfunc([NotNull] BasicParser.LenfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.lenfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLenfunc([NotNull] BasicParser.LenfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.ascfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAscfunc([NotNull] BasicParser.AscfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.ascfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAscfunc([NotNull] BasicParser.AscfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.midfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMidfunc([NotNull] BasicParser.MidfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.midfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMidfunc([NotNull] BasicParser.MidfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.pdlfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPdlfunc([NotNull] BasicParser.PdlfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.pdlfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPdlfunc([NotNull] BasicParser.PdlfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.peekfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPeekfunc([NotNull] BasicParser.PeekfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.peekfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPeekfunc([NotNull] BasicParser.PeekfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.intfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntfunc([NotNull] BasicParser.IntfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.intfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntfunc([NotNull] BasicParser.IntfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.spcfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpcfunc([NotNull] BasicParser.SpcfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.spcfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpcfunc([NotNull] BasicParser.SpcfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.frefunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFrefunc([NotNull] BasicParser.FrefuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.frefunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFrefunc([NotNull] BasicParser.FrefuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.posfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPosfunc([NotNull] BasicParser.PosfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.posfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPosfunc([NotNull] BasicParser.PosfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.usrfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsrfunc([NotNull] BasicParser.UsrfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.usrfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsrfunc([NotNull] BasicParser.UsrfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.leftfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeftfunc([NotNull] BasicParser.LeftfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.leftfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeftfunc([NotNull] BasicParser.LeftfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.rightfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRightfunc([NotNull] BasicParser.RightfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.rightfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRightfunc([NotNull] BasicParser.RightfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.strfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStrfunc([NotNull] BasicParser.StrfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.strfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStrfunc([NotNull] BasicParser.StrfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.fnfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnfunc([NotNull] BasicParser.FnfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.fnfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnfunc([NotNull] BasicParser.FnfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.valfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValfunc([NotNull] BasicParser.ValfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.valfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValfunc([NotNull] BasicParser.ValfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.scrnfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScrnfunc([NotNull] BasicParser.ScrnfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.scrnfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScrnfunc([NotNull] BasicParser.ScrnfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.sinfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSinfunc([NotNull] BasicParser.SinfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.sinfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSinfunc([NotNull] BasicParser.SinfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.cosfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCosfunc([NotNull] BasicParser.CosfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.cosfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCosfunc([NotNull] BasicParser.CosfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.tanfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTanfunc([NotNull] BasicParser.TanfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.tanfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTanfunc([NotNull] BasicParser.TanfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.atnfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtnfunc([NotNull] BasicParser.AtnfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.atnfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtnfunc([NotNull] BasicParser.AtnfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.rndfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRndfunc([NotNull] BasicParser.RndfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.rndfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRndfunc([NotNull] BasicParser.RndfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.sgnfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSgnfunc([NotNull] BasicParser.SgnfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.sgnfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSgnfunc([NotNull] BasicParser.SgnfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.expfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpfunc([NotNull] BasicParser.ExpfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.expfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpfunc([NotNull] BasicParser.ExpfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.logfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogfunc([NotNull] BasicParser.LogfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.logfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogfunc([NotNull] BasicParser.LogfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.absfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbsfunc([NotNull] BasicParser.AbsfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.absfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbsfunc([NotNull] BasicParser.AbsfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.tabfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTabfunc([NotNull] BasicParser.TabfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.tabfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTabfunc([NotNull] BasicParser.TabfuncContext context);
}
} // namespace JesseFreeman.BasicInterpreter.AntlrGenerated
