//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Basic.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace JesseFreeman.BasicInterpreter.AntlrGenerated {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBasicListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class BasicBaseListener : IBasicListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] BasicParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] BasicParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] BasicParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] BasicParser.LineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.lineWithoutNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLineWithoutNumber([NotNull] BasicParser.LineWithoutNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.lineWithoutNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLineWithoutNumber([NotNull] BasicParser.LineWithoutNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.amperoper"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmperoper([NotNull] BasicParser.AmperoperContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.amperoper"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmperoper([NotNull] BasicParser.AmperoperContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.linenumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinenumber([NotNull] BasicParser.LinenumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.linenumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinenumber([NotNull] BasicParser.LinenumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.amprstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmprstmt([NotNull] BasicParser.AmprstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.amprstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmprstmt([NotNull] BasicParser.AmprstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] BasicParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] BasicParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.vardecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVardecl([NotNull] BasicParser.VardeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.vardecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVardecl([NotNull] BasicParser.VardeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.printstmt1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintstmt1([NotNull] BasicParser.Printstmt1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.printstmt1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintstmt1([NotNull] BasicParser.Printstmt1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.exprWithSeparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprWithSeparator([NotNull] BasicParser.ExprWithSeparatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.exprWithSeparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprWithSeparator([NotNull] BasicParser.ExprWithSeparatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.separator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeparator([NotNull] BasicParser.SeparatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.separator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeparator([NotNull] BasicParser.SeparatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.getstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGetstmt([NotNull] BasicParser.GetstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.getstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGetstmt([NotNull] BasicParser.GetstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.letstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLetstmt([NotNull] BasicParser.LetstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.letstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLetstmt([NotNull] BasicParser.LetstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.variableassignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableassignment([NotNull] BasicParser.VariableassignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.variableassignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableassignment([NotNull] BasicParser.VariableassignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.stringVarDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringVarDecl([NotNull] BasicParser.StringVarDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.stringVarDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringVarDecl([NotNull] BasicParser.StringVarDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.relop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelop([NotNull] BasicParser.RelopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.relop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelop([NotNull] BasicParser.RelopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.neq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNeq([NotNull] BasicParser.NeqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.neq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNeq([NotNull] BasicParser.NeqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfstmt([NotNull] BasicParser.IfstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfstmt([NotNull] BasicParser.IfstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.forstmt1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForstmt1([NotNull] BasicParser.Forstmt1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.forstmt1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForstmt1([NotNull] BasicParser.Forstmt1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.forstmt2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForstmt2([NotNull] BasicParser.Forstmt2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.forstmt2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForstmt2([NotNull] BasicParser.Forstmt2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.nextstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNextstmt([NotNull] BasicParser.NextstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.nextstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNextstmt([NotNull] BasicParser.NextstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.inputstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputstmt([NotNull] BasicParser.InputstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.inputstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputstmt([NotNull] BasicParser.InputstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.readstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReadstmt([NotNull] BasicParser.ReadstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.readstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReadstmt([NotNull] BasicParser.ReadstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.dimstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDimstmt([NotNull] BasicParser.DimstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.dimstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDimstmt([NotNull] BasicParser.DimstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.gotostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotostmt([NotNull] BasicParser.GotostmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.gotostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotostmt([NotNull] BasicParser.GotostmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.gosubstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGosubstmt([NotNull] BasicParser.GosubstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.gosubstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGosubstmt([NotNull] BasicParser.GosubstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.pokestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPokestmt([NotNull] BasicParser.PokestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.pokestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPokestmt([NotNull] BasicParser.PokestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.callstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallstmt([NotNull] BasicParser.CallstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.callstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallstmt([NotNull] BasicParser.CallstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.hplotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHplotstmt([NotNull] BasicParser.HplotstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.hplotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHplotstmt([NotNull] BasicParser.HplotstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.vplotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVplotstmt([NotNull] BasicParser.VplotstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.vplotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVplotstmt([NotNull] BasicParser.VplotstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.plotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlotstmt([NotNull] BasicParser.PlotstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.plotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlotstmt([NotNull] BasicParser.PlotstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.ongotostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOngotostmt([NotNull] BasicParser.OngotostmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.ongotostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOngotostmt([NotNull] BasicParser.OngotostmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.ongosubstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOngosubstmt([NotNull] BasicParser.OngosubstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.ongosubstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOngosubstmt([NotNull] BasicParser.OngosubstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.vtabstmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVtabstmnt([NotNull] BasicParser.VtabstmntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.vtabstmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVtabstmnt([NotNull] BasicParser.VtabstmntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.htabstmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtabstmnt([NotNull] BasicParser.HtabstmntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.htabstmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtabstmnt([NotNull] BasicParser.HtabstmntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.himemstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHimemstmt([NotNull] BasicParser.HimemstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.himemstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHimemstmt([NotNull] BasicParser.HimemstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.lomemstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLomemstmt([NotNull] BasicParser.LomemstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.lomemstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLomemstmt([NotNull] BasicParser.LomemstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.datastmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatastmt([NotNull] BasicParser.DatastmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.datastmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatastmt([NotNull] BasicParser.DatastmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.datum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatum([NotNull] BasicParser.DatumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.datum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatum([NotNull] BasicParser.DatumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.waitstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWaitstmt([NotNull] BasicParser.WaitstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.waitstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWaitstmt([NotNull] BasicParser.WaitstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.xdrawstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXdrawstmt([NotNull] BasicParser.XdrawstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.xdrawstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXdrawstmt([NotNull] BasicParser.XdrawstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.drawstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDrawstmt([NotNull] BasicParser.DrawstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.drawstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDrawstmt([NotNull] BasicParser.DrawstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.defstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefstmt([NotNull] BasicParser.DefstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.defstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefstmt([NotNull] BasicParser.DefstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.tabstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTabstmt([NotNull] BasicParser.TabstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.tabstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTabstmt([NotNull] BasicParser.TabstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.speedstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpeedstmt([NotNull] BasicParser.SpeedstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.speedstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpeedstmt([NotNull] BasicParser.SpeedstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.rotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRotstmt([NotNull] BasicParser.RotstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.rotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRotstmt([NotNull] BasicParser.RotstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.scalestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScalestmt([NotNull] BasicParser.ScalestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.scalestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScalestmt([NotNull] BasicParser.ScalestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.colorstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColorstmt([NotNull] BasicParser.ColorstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.colorstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColorstmt([NotNull] BasicParser.ColorstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.hcolorstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHcolorstmt([NotNull] BasicParser.HcolorstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.hcolorstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHcolorstmt([NotNull] BasicParser.HcolorstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.hlinstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHlinstmt([NotNull] BasicParser.HlinstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.hlinstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHlinstmt([NotNull] BasicParser.HlinstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.vlinstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVlinstmt([NotNull] BasicParser.VlinstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.vlinstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVlinstmt([NotNull] BasicParser.VlinstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.onerrstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOnerrstmt([NotNull] BasicParser.OnerrstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.onerrstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOnerrstmt([NotNull] BasicParser.OnerrstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.prstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrstmt([NotNull] BasicParser.PrstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.prstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrstmt([NotNull] BasicParser.PrstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.instmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstmt([NotNull] BasicParser.InstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.instmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstmt([NotNull] BasicParser.InstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.storestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStorestmt([NotNull] BasicParser.StorestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.storestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStorestmt([NotNull] BasicParser.StorestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.recallstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecallstmt([NotNull] BasicParser.RecallstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.recallstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecallstmt([NotNull] BasicParser.RecallstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.liststmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListstmt([NotNull] BasicParser.ListstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.liststmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListstmt([NotNull] BasicParser.ListstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.popstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPopstmt([NotNull] BasicParser.PopstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.popstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPopstmt([NotNull] BasicParser.PopstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.amptstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmptstmt([NotNull] BasicParser.AmptstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.amptstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmptstmt([NotNull] BasicParser.AmptstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.includestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncludestmt([NotNull] BasicParser.IncludestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.includestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncludestmt([NotNull] BasicParser.IncludestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.endstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndstmt([NotNull] BasicParser.EndstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.endstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndstmt([NotNull] BasicParser.EndstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.returnstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnstmt([NotNull] BasicParser.ReturnstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.returnstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnstmt([NotNull] BasicParser.ReturnstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.restorestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRestorestmt([NotNull] BasicParser.RestorestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.restorestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRestorestmt([NotNull] BasicParser.RestorestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] BasicParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] BasicParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.func_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_([NotNull] BasicParser.Func_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.func_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_([NotNull] BasicParser.Func_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.signExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSignExpression([NotNull] BasicParser.SignExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.signExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSignExpression([NotNull] BasicParser.SignExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.exponentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExponentExpression([NotNull] BasicParser.ExponentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.exponentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExponentExpression([NotNull] BasicParser.ExponentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.multiplyingExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplyingExpression([NotNull] BasicParser.MultiplyingExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.multiplyingExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplyingExpression([NotNull] BasicParser.MultiplyingExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.addingExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddingExpression([NotNull] BasicParser.AddingExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.addingExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddingExpression([NotNull] BasicParser.AddingExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] BasicParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] BasicParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] BasicParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] BasicParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.var_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_([NotNull] BasicParser.Var_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.var_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_([NotNull] BasicParser.Var_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.varname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarname([NotNull] BasicParser.VarnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.varname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarname([NotNull] BasicParser.VarnameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.varsuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarsuffix([NotNull] BasicParser.VarsuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.varsuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarsuffix([NotNull] BasicParser.VarsuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarlist([NotNull] BasicParser.VarlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarlist([NotNull] BasicParser.VarlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.exprlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprlist([NotNull] BasicParser.ExprlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.exprlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprlist([NotNull] BasicParser.ExprlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.sqrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSqrfunc([NotNull] BasicParser.SqrfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.sqrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSqrfunc([NotNull] BasicParser.SqrfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.chrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChrfunc([NotNull] BasicParser.ChrfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.chrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChrfunc([NotNull] BasicParser.ChrfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.lenfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLenfunc([NotNull] BasicParser.LenfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.lenfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLenfunc([NotNull] BasicParser.LenfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.ascfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAscfunc([NotNull] BasicParser.AscfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.ascfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAscfunc([NotNull] BasicParser.AscfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.midfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMidfunc([NotNull] BasicParser.MidfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.midfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMidfunc([NotNull] BasicParser.MidfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.pdlfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPdlfunc([NotNull] BasicParser.PdlfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.pdlfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPdlfunc([NotNull] BasicParser.PdlfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.peekfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPeekfunc([NotNull] BasicParser.PeekfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.peekfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPeekfunc([NotNull] BasicParser.PeekfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.intfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntfunc([NotNull] BasicParser.IntfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.intfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntfunc([NotNull] BasicParser.IntfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.spcfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpcfunc([NotNull] BasicParser.SpcfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.spcfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpcfunc([NotNull] BasicParser.SpcfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.frefunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrefunc([NotNull] BasicParser.FrefuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.frefunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrefunc([NotNull] BasicParser.FrefuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.posfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPosfunc([NotNull] BasicParser.PosfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.posfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPosfunc([NotNull] BasicParser.PosfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.usrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsrfunc([NotNull] BasicParser.UsrfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.usrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsrfunc([NotNull] BasicParser.UsrfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.leftfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeftfunc([NotNull] BasicParser.LeftfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.leftfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeftfunc([NotNull] BasicParser.LeftfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.rightfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRightfunc([NotNull] BasicParser.RightfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.rightfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRightfunc([NotNull] BasicParser.RightfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.strfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrfunc([NotNull] BasicParser.StrfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.strfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrfunc([NotNull] BasicParser.StrfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.fnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnfunc([NotNull] BasicParser.FnfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.fnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnfunc([NotNull] BasicParser.FnfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.valfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValfunc([NotNull] BasicParser.ValfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.valfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValfunc([NotNull] BasicParser.ValfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.scrnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScrnfunc([NotNull] BasicParser.ScrnfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.scrnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScrnfunc([NotNull] BasicParser.ScrnfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.sinfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSinfunc([NotNull] BasicParser.SinfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.sinfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSinfunc([NotNull] BasicParser.SinfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.cosfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCosfunc([NotNull] BasicParser.CosfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.cosfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCosfunc([NotNull] BasicParser.CosfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.tanfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTanfunc([NotNull] BasicParser.TanfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.tanfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTanfunc([NotNull] BasicParser.TanfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.atnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtnfunc([NotNull] BasicParser.AtnfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.atnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtnfunc([NotNull] BasicParser.AtnfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.rndfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRndfunc([NotNull] BasicParser.RndfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.rndfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRndfunc([NotNull] BasicParser.RndfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.sgnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSgnfunc([NotNull] BasicParser.SgnfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.sgnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSgnfunc([NotNull] BasicParser.SgnfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.expfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpfunc([NotNull] BasicParser.ExpfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.expfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpfunc([NotNull] BasicParser.ExpfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.logfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogfunc([NotNull] BasicParser.LogfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.logfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogfunc([NotNull] BasicParser.LogfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.absfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbsfunc([NotNull] BasicParser.AbsfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.absfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbsfunc([NotNull] BasicParser.AbsfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicParser.tabfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTabfunc([NotNull] BasicParser.TabfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicParser.tabfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTabfunc([NotNull] BasicParser.TabfuncContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace JesseFreeman.BasicInterpreter.AntlrGenerated
